# change the followings to match your Github username and repo name
baseurl: "/muhammadkhezar" # the name of your github repo
url: "https://imkhezar.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Muhammad Khezar | The IT Freelancer"
description: Software Engineer | Top Rated Freelancer | Digital Marketer | Developer

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Muhammad Khezar
author-bio: Software Engineer  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Hire me
  permalink: hireme
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Muhammad Khezar"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
